### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by b1naryTR** [zhaodice/qemu-anti-detection#1]
I have successfully compiled the thing, what do I do after compiling it?
Please help. Thanks.

**Comment by b1naryTR** [comment]
After doing make install, I got "domain configration does not support video model 'xql'. When I tried to change it, I got "USB redirection is not supported by this version of QEMU." I tried both 6.2.0 and 7.0.0. Both are same, original version were working fine.

**Comment by b1naryTR** [comment]
is there any way to enable evertyhing or do I have to enter every parameter one by one?

**Comment by b1naryTR** [comment]
I got error "ERROR: Dependency "spice-server" not found, tried pkgconfig" when I tried your example command.

**Comment by b1naryTR** [comment]
Now I have "ERROR: Dependency "libusbredirparser-0.5" not found, tried pkgconfig". Is there any way to download all dependencies at once?

**Comment by b1naryTR** [comment]
Oh I just solved it myself, installed package "libusbredirparser-dev"

**Comment by b1naryTR** [comment]
Oh btw I am trying to get valorant running on kvm, is there any crypology thingy I need to enable? Because my virtual TPM chip cannot prove file ownership.

**Comment by b1naryTR** [comment]
I just finished compiling, it still shows same error sadly.

**Comment by b1naryTR** [comment]
I know about that, usb and xql are still fucked though

**Comment by b1naryTR** [comment]
tf, how did you do that? When I tried it I could not bind pci devices

**Comment by b1naryTR** [comment]
I have "5.15.0-48-generic" as uname says. I guess it is ok?

Uname -a output:
Linux TULPAR-T5-V19-2 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by b1naryTR** [comment]
I probably have MUXless laptop, because in windows when I disable iGPU, screen goes to 30hz instead of 144.

**Comment by b1naryTR** [comment]
Is there any way to install optimus-manager on ubuntu? There are only tutorials for arch. But there was something-switch included inside nvidia drivers.

**Comment by b1naryTR** [comment]
Oh and usb thingy still isn't working

**Comment by b1naryTR** [comment]
I am going to lose my mind, on build spice protocol and server support are marked yes but I can't fucking use spice. And xml editor on virt-manager doesn't work!!! When I enable xml editing on preferences it DOESN'T FUCKING WORK

**Comment by b1naryTR** [comment]
When I tried to remove usb redirectors it asks me to save the changes but I FUCKING CHANGED GPU SETTINGS and it doesn't apply either of them, just throws an error.

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by b1naryTR** [comment]
I tried to create new machine but I can't. Because fuck me.

Unable to complete install: 'internal error: cannot update AppArmor profile 'libvirt-865576b2-ee2f-46e9-8b6e-9a79bcc35c38''

**Comment by b1naryTR** [comment]
Looks like it's an XML problem but not sure how to fix it. I must say that it was working fine without patch and modified build.

Here is the log:
```
Unable to complete install: 'internal error: cannot update AppArmor profile 'libvirt-62565ea6-8ade-4039-a816-91da6d9f5e91''

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4400, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: internal error: cannot update AppArmor profile 'libvirt-62565ea6-8ade-4039-a816-91da6d9f5e91'
```

**Comment by nhamhuynh79** [comment]
> ![Screenshot_20221004_021656](https://user-images.githubusercontent.com/63996691/193649475-11db7dee-7d13-48db-bc5d-dfd45c926625.png) this is my passthough result

Hello, How connect to virt-manager?
I have this error : 
error: Failed to define domain from win10.xml
error: internal error: Failed to start QEMU binary /usr/local/bin/qemu-system-x86_64 for probing: libvirt:  error : cannot execute binary /usr/local/bin/qemu-system-x86_64: Permission denied

**Comment by zhaodice** [comment]
> /usr/local/bin/qemu-system-x86_64

chmod +x /usr/local/bin/qemu-system-x86_64
