### ISSUE TITLE
USB redirection is not supported by this version of QEMU  

### ISSUE THREAD

**Issue by zzz-97** [zhaodice/qemu-anti-detection#53]
启动虚拟机时会报错 或者 修改xml

unsupported configuration: USB redirection is not supported by this version of QEMU

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/delete.py", line 338, in remove_devobj_internal
    vm.remove_device(devobj)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 623, in remove_device
    self._redefine_xmlobj(xmlobj)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 391, in _redefine_xmlobj
    self._redefine_xml_internal(origxml, newxml)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 374, in _redefine_xml_internal
    self._define(newxml)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1119, in _define
    self.conn.define_domain(xml)
  File "/usr/share/virt-manager/virtManager/connection.py", line 554, in define_domain
    return self._backend.defineXML(xml)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4414, in defineXML
    raise libvirtError('virDomainDefineXML() failed')
libvirt.libvirtError: unsupported configuration: USB redirection is not supported by this version of QEMU

是要修改哪个补丁文件的usb重定向配置 来支持吗

**Comment by zhaodice** [comment]
编译qemu的时候那个configuration有一堆模块配置，要把usb重定向那个模块，我忘记叫什么名字了，反正要enable然后才能编译进去才有这个功能
