### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by pplegends** [zhaodice/qemu-anti-detection#74]
i got this error when doing this line:sudo make install -j$(nproc)
what i do wrong/ what i need to do to fix this, thx for the help

the errors:
changing dir to build for make "install"...
make[1]: Entering directory '/home/munf/git-build/qemu-8.2.2/build'
ninja: no work to do.
/home/munf/git-build/qemu-8.2.2/build/pyvenv/bin/meson introspect --targets --tests --benchmarks | /home/munf/git-build/qemu-8.2.2/build/pyvenv/bin/python3 -B scripts/mtest2make.py > Makefile.mtest
[1/9613] Generating from '/home/munf/git-build/qemu-8.2.2/target/hexagon/idef-parser/idef-parser.lex'
[2/9613] Generating trace/trace-crypto.c with a custom command
[3/9613] Generating trace/trace-qapi.c with a custom command
[4/9613] Generating trace/trace-crypto.h with a custom command
[5/9613] Generating trace/trace-root.h with a custom command
[6/9613] Generating trace/trace-root.c with a custom command
[7/9613] Generating trace/trace-qom.h with a custom command
[8/9613] Generating trace/trace-qapi.h with a custom command
[9/9613] Generating trace/trace-qom.c with a custom command
[10/9613] Generating trace/trace-monitor.h with a custom command
[11/9613] Generating trace/trace-monitor.c with a custom command
[12/9613] Generating qemu-version.h with a custom command (wrapped by meson to capture output)
[13/9613] Generating qemu-img-cmds.h with a custom command (wrapped by meson to capture output)
[14/9613] Generating hmp-commands-info.h with a custom command (wrapped by meson to capture output)
[15/9613] Generating trace/trace-util.c with a custom command
[16/9613] Generating trace/trace-util.h with a custom command
[17/9613] Generating trace/trace-gdbstub.h with a custom command
[18/9613] Generating trace/trace-gdbstub.c with a custom command
[19/9613] Generating trace/trace-linux_user.c with a custom command
[20/9613] Generating trace/trace-linux_user.h with a custom command
[21/9613] Generating hmp-commands.h with a custom command (wrapped by meson to capture output)
[22/9613] Generating trace/trace-authz.h with a custom command
[23/9613] Generating trace/trace-authz.c with a custom command
[24/9613] Generating config-poison.h with a custom command (wrapped by meson to capture output)
[25/9613] Generating trace/trace-io.c with a custom command
[26/9613] Generating trace/trace-io.h with a custom command
[27/9613] Generating trace/trace-block.c with a custom command
[28/9613] Generating trace/trace-nbd.c with a custom command
[29/9613] Generating trace/trace-scsi.h with a custom command
[30/9613] Generating trace/trace-scsi.c with a custom command
[31/9613] Generating trace/trace-accel_kvm.c with a custom command
[32/9613] Generating trace/trace-block.h with a custom command
[33/9613] Generating trace/trace-nbd.h with a custom command
[34/9613] Generating trace/trace-accel_kvm.h with a custom command
[35/9613] Generating trace/trace-audio.h with a custom command
[36/9613] Generating trace/trace-audio.c with a custom command
[37/9613] Generating qemu-options.def with a custom command (wrapped by meson to capture output)
[38/9613] Generating trace/trace-backends.h with a custom command
[39/9613] Generating trace/trace-backends.c with a custom command
[40/9613] Generating trace/trace-backends_tpm.c with a custom command
[41/9613] Generating trace/trace-chardev.h with a custom command
[42/9613] Generating trace/trace-chardev.c with a custom command
[43/9613] Generating trace/trace-backends_tpm.h with a custom command
[44/9613] Generating trace/trace-ebpf.h with a custom command
[45/9613] Generating trace/trace-ebpf.c with a custom command
[46/9613] Generating trace/trace-hw_9pfs.c with a custom command
[47/9613] Generating trace/trace-hw_acpi.c with a custom command
[48/9613] Generating trace/trace-hw_9pfs.h with a custom command
[49/9613] Generating from '/home/munf/git-build/qemu-8.2.2/target/hexagon/idef-parser/idef-parser.y'
[50/9613] Generating trace/trace-hw_adc.h with a custom command
[51/9613] Generating trace/trace-hw_acpi.h with a custom command
[52/9613] Generating trace/trace-hw_adc.c with a custom command
[53/9613] Generating trace/trace-hw_alpha.h with a custom command
[54/9613] Generating trace/trace-hw_alpha.c with a custom command
[55/9613] Generating trace/trace-hw_arm.c with a custom command
[56/9613] Generating trace/trace-hw_audio.c with a custom command
[57/9613] Generating trace/trace-hw_arm.h with a custom command
[58/9613] Generating trace/trace-hw_audio.h with a custom command
[59/9613] Generating trace/trace-hw_block_dataplane.h with a custom command
[60/9613] Generating trace/trace-hw_block.c with a custom command
[61/9613] Generating trace/trace-hw_block.h with a custom command
[62/9613] Generating trace/trace-hw_block_dataplane.c with a custom command
[63/9613] Generating trace/trace-hw_char.c with a custom command
[64/9613] Generating trace/trace-hw_display.c with a custom command
[65/9613] Generating trace/trace-hw_char.h with a custom command
[66/9613] Generating trace/trace-hw_dma.c with a custom command
[67/9613] Generating trace/trace-hw_dma.h with a custom command
[68/9613] Generating trace/trace-hw_display.h with a custom command
[69/9613] Generating trace/trace-hw_hyperv.h with a custom command
[70/9613] Generating trace/trace-hw_hyperv.c with a custom command
[71/9613] Generating trace/trace-hw_i2c.h with a custom command
[72/9613] Generating trace/trace-hw_i2c.c with a custom command
[73/9613] Generating trace/trace-hw_i386_xen.h with a custom command
[74/9613] Generating trace/trace-hw_i386.c with a custom command
[75/9613] Generating trace/trace-hw_i386_xen.c with a custom command
[76/9613] Generating trace/trace-hw_i386.h with a custom command
[77/9613] Generating trace/trace-hw_i386_kvm.c with a custom command
[78/9613] Generating trace/trace-hw_i386_kvm.h with a custom command
[79/9613] Generating trace/trace-hw_ide.c with a custom command
[80/9613] Generating trace/trace-hw_input.c with a custom command
[81/9613] Generating trace/trace-hw_input.h with a custom command
[82/9613] Generating trace/trace-hw_ide.h with a custom command
[83/9613] Generating trace/trace-hw_isa.h with a custom command
[84/9613] Generating trace/trace-hw_isa.c with a custom command
[85/9613] Generating trace/trace-hw_intc.c with a custom command
[86/9613] Generating trace/trace-hw_mem.c with a custom command
[87/9613] Generating trace/trace-hw_mem.h with a custom command
[88/9613] Generating trace/trace-hw_mips.h with a custom command
[89/9613] Generating trace/trace-hw_mips.c with a custom command
[90/9613] Generating trace/trace-hw_intc.h with a custom command
[91/9613] Generating trace/trace-hw_misc_macio.h with a custom command
[92/9613] Generating trace/trace-hw_misc.c with a custom command
[93/9613] Generating trace/trace-hw_misc_macio.c with a custom command
[94/9613] Generating trace/trace-hw_net_can.h with a custom command
[95/9613] Generating trace/trace-hw_net_can.c with a custom command
[96/9613] Generating trace/trace-hw_nubus.c with a custom command
[97/9613] Generating trace/trace-hw_misc.h with a custom command
[98/9613] Generating trace/trace-hw_net.c with a custom command
[99/9613] Generating trace/trace-hw_nubus.h with a custom command
[100/9613] Generating trace/trace-hw_nvram.h with a custom command
[101/9613] Generating trace/trace-hw_nvram.c with a custom command
[102/9613] Generating trace/trace-hw_nvme.c with a custom command
[103/9613] Generating trace/trace-hw_pci.c with a custom command
[104/9613] Generating trace/trace-hw_pci.h with a custom command
[105/9613] Generating trace/trace-hw_pci_host.h with a custom command
[106/9613] Generating trace/trace-hw_pci_host.c with a custom command
[107/9613] Generating trace/trace-hw_nvme.h with a custom command
[108/9613] Generating trace/trace-hw_ppc.c with a custom command
[109/9613] Generating trace/trace-hw_net.h with a custom command
[110/9613] Generating trace/trace-hw_rdma.h with a custom command
[111/9613] Generating trace/trace-hw_rdma.c with a custom command
[112/9613] Generating trace/trace-hw_rdma_vmw.h with a custom command
[113/9613] Generating trace/trace-hw_rdma_vmw.c with a custom command
[114/9613] Generating trace/trace-hw_ppc.h with a custom command
[115/9613] Generating trace/trace-hw_rtc.h with a custom command
[116/9613] Generating trace/trace-hw_rtc.c with a custom command
[117/9613] Generating trace/trace-hw_s390x.h with a custom command
[118/9613] Generating trace/trace-hw_s390x.c with a custom command
[119/9613] Generating trace/trace-hw_sd.c with a custom command
[120/9613] Generating trace/trace-hw_sh4.h with a custom command
[121/9613] Generating trace/trace-hw_sh4.c with a custom command
[122/9613] Generating trace/trace-hw_sparc.c with a custom command
[123/9613] Generating trace/trace-hw_scsi.c with a custom command
[124/9613] Generating trace/trace-hw_sd.h with a custom command
[125/9613] Generating trace/trace-hw_sparc.h with a custom command
[126/9613] Generating trace/trace-hw_sparc64.h with a custom command
[127/9613] Generating trace/trace-hw_sparc64.c with a custom command
[128/9613] Generating trace/trace-hw_ssi.h with a custom command
[129/9613] Generating trace/trace-hw_ssi.c with a custom command
[130/9613] Generating trace/trace-hw_scsi.h with a custom command
[131/9613] Generating trace/trace-hw_timer.c with a custom command
[132/9613] Generating trace/trace-hw_tpm.h with a custom command
[133/9613] Generating trace/trace-hw_tpm.c with a custom command
[134/9613] Generating trace/trace-hw_ufs.c with a custom command
[135/9613] Generating trace/trace-hw_ufs.h with a custom command
[136/9613] Generating trace/trace-hw_timer.h with a custom command
[137/9613] Generating trace/trace-hw_vfio.c with a custom command
[138/9613] Generating trace/trace-hw_usb.c with a custom command
[139/9613] Generating trace/trace-hw_virtio.c with a custom command
[140/9613] Generating trace/trace-hw_watchdog.c with a custom command
[141/9613] Generating trace/trace-hw_watchdog.h with a custom command
[142/9613] Generating trace/trace-hw_vfio.h with a custom command
[143/9613] Generating trace/trace-hw_virtio.h with a custom command
[144/9613] Generating trace/trace-hw_xen.c with a custom command
[145/9613] Generating trace/trace-hw_xen.h with a custom command
[146/9613] Generating trace/trace-hw_gpio.h with a custom command
[147/9613] Generating trace/trace-hw_gpio.c with a custom command
[148/9613] Generating trace/trace-hw_usb.h with a custom command
[149/9613] Generating trace/trace-net.h with a custom command
[150/9613] Generating trace/trace-net.c with a custom command
[151/9613] Generating trace/trace-migration.c with a custom command
[152/9613] Generating trace/trace-system.h with a custom command
[153/9613] Generating trace/trace-system.c with a custom command
[154/9613] Generating trace/trace-hw_remote.h with a custom command
[155/9613] Generating trace/trace-ui.c with a custom command
[156/9613] Generating trace/trace-hw_remote.c with a custom command
[157/9613] Generating trace/trace-accel_tcg.h with a custom command
[158/9613] Generating trace/trace-ui.h with a custom command
[159/9613] Generating trace/trace-migration.h with a custom command
[160/9613] Generating trace/trace-accel_tcg.c with a custom command
[161/9613] Generating trace/trace-hw_core.h with a custom command
[162/9613] Generating trace/trace-hw_core.c with a custom command
[163/9613] Generating trace/trace-target_arm.h with a custom command
[164/9613] Generating trace/trace-target_arm.c with a custom command
[165/9613] Generating trace/trace-target_arm_hvf.c with a custom command
[166/9613] Generating trace/trace-target_hppa.h with a custom command
[167/9613] Generating trace/trace-target_arm_hvf.h with a custom command
[168/9613] Generating trace/trace-target_hppa.c with a custom command
[169/9613] Generating trace/trace-target_i386.h with a custom command
[170/9613] Generating trace/trace-target_i386.c with a custom command
[171/9613] Generating trace/trace-target_i386_kvm.h with a custom command
[172/9613] Generating trace/trace-target_i386_kvm.c with a custom command
[173/9613] Generating trace/trace-target_mips_tcg.h with a custom command
[174/9613] Generating trace/trace-target_mips_tcg.c with a custom command
[175/9613] Generating trace/trace-target_nios2.c with a custom command
[176/9613] Generating trace/trace-target_nios2.h with a custom command
[177/9613] Generating trace/trace-target_ppc.h with a custom command
[178/9613] Generating trace/trace-target_ppc.c with a custom command
[179/9613] Generating trace/trace-target_riscv.h with a custom command
[180/9613] Generating trace/trace-target_riscv.c with a custom command
[181/9613] Generating trace/trace-target_s390x.h with a custom command
[182/9613] Generating trace/trace-target_s390x.c with a custom command
[183/9613] Generating trace/trace-target_s390x_kvm.h with a custom command
[184/9613] Generating trace/trace-target_s390x_kvm.c with a custom command
[185/9613] Generating trace/trace-target_sparc.c with a custom command
[186/9613] Generating trace/trace-target_sparc.h with a custom command
[187/9613] Compiling C object target/hexagon/idef-parser.p/meson-generated_idef-parser.tab.c.o
[188/9613] Generating ui/input-keymap-qcode-to-atset2.c.inc with a custom command (wrapped by meson to capture output)
[189/9613] Generating ui/input-keymap-linux-to-qcode.c.inc with a custom command (wrapped by meson to capture output)
[190/9613] Generating ui/input-keymap-qcode-to-atset1.c.inc with a custom command (wrapped by meson to capture output)
[191/9613] Generating ui/input-keymap-qcode-to-qnum.c.inc with a custom command (wrapped by meson to capture output)
[192/9613] Generating ui/input-keymap-qcode-to-atset3.c.inc with a custom command (wrapped by meson to capture output)
[193/9613] Generating ui/input-keymap-qcode-to-linux.c.inc with a custom command (wrapped by meson to capture output)
[194/9613] Generating ui/input-keymap-qcode-to-sun.c.inc with a custom command (wrapped by meson to capture output)
[195/9613] Generating ui/input-keymap-qnum-to-qcode.c.inc with a custom command (wrapped by meson to capture output)
[196/9613] Generating ui/input-keymap-usb-to-qcode.c.inc with a custom command (wrapped by meson to capture output)
[197/9613] Generating ui/input-keymap-win32-to-qcode.c.inc with a custom command (wrapped by meson to capture output)
[198/9613] Generating ui/input-keymap-atset1-to-qcode.c.inc with a custom command (wrapped by meson to capture output)
[199/9613] Generating ui/dbus-display preprocess with a custom command (wrapped by meson to set env)
[200/9613] Generating ui/shader/texture-blit-frag.h with a custom command (wrapped by meson to capture output)
[201/9613] Generating ui/shader/texture-blit-vert.h with a custom command (wrapped by meson to capture output)
[202/9613] Generating ui/shader/texture-blit-flip-vert.h with a custom command (wrapped by meson to capture output)
[203/9613] Generating ui/input-keymap-xorgkbd-to-qcode.c.inc with a custom command (wrapped by meson to capture output)
[204/9613] Generating ui/input-keymap-xorgxquartz-to-qcode.c.inc with a custom command (wrapped by meson to capture output)
[205/9613] Generating ui/input-keymap-xorgevdev-to-qcode.c.inc with a custom command (wrapped by meson to capture output)
[206/9613] Generating ui/input-keymap-xorgxwin-to-qcode.c.inc with a custom command (wrapped by meson to capture output)
[207/9613] Generating ui/input-keymap-osx-to-qcode.c.inc with a custom command (wrapped by meson to capture output)
[208/9613] Compiling C object target/s390x/gen-features.p/gen-features.c.o
[209/9613] Generating block/module_block.h with a custom command
[210/9613] Generating ui/dbus-display gdbus-codegen with a custom command
FAILED: ui/dbus-display1.h ui/dbus-display1.c 
/usr/bin/gdbus-codegen ui/dbus-display1.xml --glib-min-required 2.64 --output-directory /home/munf/git-build/qemu-8.2.2/build/ui --interface-prefix org.qemu. --c-namespace QemuDBus --generate-c-code dbus-display1
Traceback (most recent call last):
  File "/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/share/glib-2.0/codegen/codegen_main.py", line 30, in <module>
    from . import dbustypes
  File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
[211/9613] Generating ui/input-keymap-x11-to-qcode.c.inc with a custom command (wrapped by meson to capture output)
[212/9613] Generating block/block-gen.c with a custom command
[213/9613] Linking target target/s390x/gen-features
[214/9613] Generating 'libqemu-aarch64_be-linux-user.fa.p/decode-neon-shared.c.inc'
[215/9613] Generating tests/Test QAPI files with a custom command
[216/9613] Generating aarch64_be-linux-user-gdbstub-xml.c with a custom command (wrapped by meson to capture output)
[217/9613] Compiling C object subprojects/libvhost-user/libvhost-user-glib.a.p/libvhost-user-glib.c.o
[218/9613] Compiling C object linux-user/gen-vdso.p/gen-vdso.c.o
[219/9613] Generating 'libcommon.fa.p/decode-insns.c.inc'
[220/9613] Generating qapi/shared QAPI source files with a custom command
[221/9613] Compiling C object target/hexagon/idef-parser.p/meson-generated_idef-parser.yy.c.o
[222/9613] Compiling C object target/hexagon/idef-parser.p/_home_munf_git-build_qemu-8.2.2_target_hexagon_idef-parser_parser-helpers.c.o
[223/9613] Compiling C object subprojects/libvhost-user/libvhost-user.a.p/libvhost-user.c.o
[224/9613] Compiling C object subprojects/libvduse/libvduse.a.p/libvduse.c.o
[225/9613] Compiling C object target/hexagon/gen_semantics.p/gen_semantics.c.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:162: run-ninja] Error 1
make[1]: Leaving directory '/home/munf/git-build/qemu-8.2.2/build'
make: *** [GNUmakefile:6: build] Error 2

**Comment by Samuil1337** [comment]
Can you tell us how you fixed this issue for the people in the future who encounter the same problem?

**Comment by pplegends** [comment]
in my case, i need to install this dependency: sudo pacman -S python-packaging
